version: '3'
services:
  nginx:
    restart: always
    build:
      context: ./.docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./public:/var/www/html/public
      - ./.docker/nginx/logs:/var/log/nginx
      - ./.docker/nginx/sites:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: .docker/php-fpm/Dockerfile
    volumes:
      - ./:/var/www/html:delegated
      - ./.docker/php-fpm/logs:/var/log/php
      - ./var/log:/var/www/html/var/log:cached
    networks:
      - app-network

  db:
    image: postgres:11
    restart: always
    env_file:
      - ./.docker/.env
    ports:
      - 5432:5432
    volumes:
      - ./.docker/postgres:/docker-entrypoint-initdb.d/
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
